Eve-Ship-ID/Controllers/EveShipIDQuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eve_Ship_ID.Models;
using eve_api;
using System.Text;

namespace Eve_Ship_ID.Controllers
{
    public class EveShipIDQuizController : Controller
    {
        private const int QUESTIONCOUNT = 4;
        //
        // GET: /EveShipIDQuiz/

        public ActionResult Index()
        {

            //Request.ServerVariables["HTTP_REFERER"]
            if (this.HttpContext.Request.QueryString["resetquiz"] == "1")
            {
                Request.Cookies.Remove("eveshipid.score");
            }

            //delete old cookies since score has changed?

            var cookie = Request.Cookies["eveshipid.score"];
            var score = cookie == null ? string.Empty : cookie.Value;


            var popData = new ShipQuiz();

            if (score != String.Empty)
            {
                popData = getSingleQuestion(eve_api.eve_api.QuizLevel.NORMAL,ParseOutPreviousTypeIds(score));
                popData.score = score;
            }
            else
            {
                popData = getSingleQuestion(eve_api.eve_api.QuizLevel.NORMAL);
            }

            var difficultyCookie = Request.Cookies["eveshipid.difficulty"];
            var difficulty = difficultyCookie == null ? "00" : difficultyCookie.Value;

            if (difficulty.Length == 2)
            {
                if (difficulty.Substring(0, 1) == "1")
                {
                    popData.quizDifficultyCaps = true;
                }
                if (difficulty.Substring(1, 1) == "1")
                {
                    popData.quizDifficultyPirateRare = true;
                }
            }
           
            return View(popData);
        }

        [HttpPost]
        public ActionResult Index(ShipQuiz quiz)
        {

            var endValue = quiz.endValue;
            
            var newCookie = new HttpCookie("eveshipid.score", endValue);
            var existingCookie = Request.Cookies["eveshipid.score"];

            if (existingCookie != null)
            {
                Response.SetCookie(newCookie);
            }
            else
            {
                Response.Cookies.Add(newCookie);
            }

            var difficultyString = new StringBuilder();
            difficultyString.Append(quiz.quizDifficultyCaps ? "1":"0"); 
            difficultyString.Append(quiz.quizDifficultyPirateRare ? "1":"0");

            var newDifficultCookie = new HttpCookie("eveshipid.difficulty", difficultyString.ToString());
            Response.SetCookie(newDifficultCookie);

            var previousIds = ParseOutPreviousTypeIds(endValue);

            var quizDifficulty = GetQuizLevelFromString(difficultyString.ToString());

            var popData = getSingleQuestion(quizDifficulty, previousIds);
            popData.score = endValue;
            return View(popData);
            
        }

        public string GetCorrectAnswer(string id)
        {
            //id is shipname. return value is shiptype
            try
            {
                var correctType = eve_api.eve_api.GetShipType(id);
                return correctType;
            }
            catch (Exception x)
            {
                return "Error: Ship Not Found";
            }
        }

        public string GetShipId(string id)
        {
            //id is shipname. return value is shipId
            try
            {
                var shipTypeId = eve_api.eve_api.GetShipId(id);
                return shipTypeId.ToString();
            }
            catch (Exception)
            {
                return "Error: Ship Not Found";
            }
        }

        /// <summary>
        /// Returns a list of ship names in same order as the list of ship IDs
        /// </summary>
        /// <param name="id">CSV of ship ids</param>
        /// <returns>CSV of ship names</returns>
        public string GetShipNames(string id)
        {
            try
            {
                var shipNames = eve_api.eve_api.GetShipNameCSV(id);
                return shipNames;
            }
            catch (Exception)
            {
                return "Error: ship(s) not found";
            }

        }

        public string GetShipDescription(string id)
        {
            //id is shipname. return value is shipId
            try
            {
                var shipTypeId = eve_api.eve_api.GetShipDescription(id);
                return shipTypeId;
            }
            catch (Exception)
            {
                return "Error: Ship Not Found";
            }
        }

        private ShipQuiz getSingleQuestion(eve_api.eve_api.QuizLevel quizLevel)
        {
            return getSingleQuestion(quizLevel, null);
        }

        private ShipQuiz getSingleQuestion(eve_api.eve_api.QuizLevel quizLevel, List<int> alreadyAnswered)
        {
            var rand = new Random();
            var maxIdx = QUESTIONCOUNT-1;
            var correctItem = rand.Next(0, maxIdx+1); //random.Next upper bound is exclusive
            System.Diagnostics.Debug.Print("Correct item is " + correctItem);

            var shipName = eve_api.eve_api.GetRandomShip(1,alreadyAnswered, quizLevel)[0];
            var correctType = new List<string>();
            correctType.Add(eve_api.eve_api.GetShipType(shipName)); //this will be our correct answer
            
            var rawShipTypes = eve_api.eve_api.GetRandomShipType(maxIdx, quizLevel,null,null,correctType);
            
            var shipTypes = new List<string>();
            var j = 0;
            foreach(var s in rawShipTypes)
            {
                if (j != correctItem)
                {
                    shipTypes.Add(s);
                }
                else
                {
                    shipTypes.Add(correctType[0]);
                    shipTypes.Add(s);
                }
                j++;
            }
            if (correctItem == maxIdx) //it's the last option, so was not hit in the foreach above
            {
                shipTypes.Add(correctType[0]);
            }

            return new ShipQuiz { ShipName = shipName, ShipTypeOptions = shipTypes };
        }

        private List<int> ParseOutPreviousTypeIds(string scoreStr)
        {
            var previousIds = new List<int>();


            if (scoreStr.Length > 0)
            {
                var previousIdArray = scoreStr.Split(new string[] { "|" }, StringSplitOptions.RemoveEmptyEntries);
                for (var i = 0; i < previousIdArray.Length; i++)
                {
                    if (i % 2 == 0)
                    {
                        var id = 0;
                        if (Int32.TryParse(previousIdArray[i], out id)) 
                        { 
                            previousIds.Add(id); 
                        }
                    }
                }
            }
            return previousIds;
        }

        /// <summary>
        /// Takes a 2-character string and parses to Quiz level. e.g. 00 for normal, 10 for Caps, 01 for pirate/rare, 11 for all three)
        /// </summary>
        /// <param name="quizLevel"></param>
        private eve_api.eve_api.QuizLevel GetQuizLevelFromString(string quizLevel)
        {
            var ql = eve_api.eve_api.QuizLevel.NORMAL;

            if (quizLevel.Length == 2)
            {
                var caps = (quizLevel.Substring(0, 1) == "1");
                var pirate = (quizLevel.Substring(1, 1) == "1");
                if (caps && pirate) { ql = eve_api.eve_api.QuizLevel.CAPSPIRATE; }
                if (caps && !pirate) { ql = eve_api.eve_api.QuizLevel.CAPS; }
                if (!caps && pirate) { ql = eve_api.eve_api.QuizLevel.PIRATE; }
                if (!caps && !pirate) { ql = eve_api.eve_api.QuizLevel.NORMAL; }
            }

            return ql;
        }

       
    }
}

Eve-Ship-ID/Views/EveShipIDQuiz/Index.cshtml
@model Eve_Ship_ID.Models.ShipQuiz

@{
    ViewBag.Title = "EVE Online Ship Identification Quiz";
}
<script>


    function NextQuestion() {
//        
//        score = $("#endValue").val();
//        var scoreArray = score.split(";");
//        nbrAnswered = (scoreArray.length-1) / 2;  //trailing ; makes a blank entry so subtract one
//        //alert(nbrAnswered);
        var nbrAnswered = GetNbrAnswered();

        if (($("#completionstatus").text() == "nextquestion")) {
            if (nbrAnswered < 20) {
                nextQuestionForm.submit();
            }
            else {
                //var resultrows = GetFinalScoreHTML();

                $("#shipdescription").css("display", "none");
                $("#innerquiz").css("display", "none");
                $("#currentscore").css("display", "none");
                $("#startoverlink").css("display", "none");
                $("#score").css("display", "none");
                //$("#resultstable").append("");
                //$("#resultstable").append(resultrows);
                $("#quizresults").css("display", "inline-block");
                //$("#quizresults").css("border-style", "dashed");
                
            }
        }
       
    }


    function HandleAnswer() {
        $("#mainformSubmit").css("display", "none");  //no such control?

        //$("#qmarkspan").css("display", "none");
        $("#qmarkdiv").css("display", "none");
        $("#shipdescription").css("display", "inline-block");

        question = "@Model.ShipName";

        answer = $("input[type='radio'][name='typeOption']:checked").val();

        $.get("/EveShipIDQuiz/GetCorrectAnswer", { id: question })
        .done(function (correctanswer) {
            $("#correctshipname").prepend(correctanswer);
            shipDesc = $.get("/EveShipIDQuiz/GetShipDescription", { id: question })
            .done(function (descr) {
                $("#shipdescp").append("<br/><br/>");
                $("#shipdescp").css("font-weight", "normal");
                $("#shipdescp").css("font-size", "small");
                $("#shipdescp").append(descr);
                //$("#shipdescription").css("display", "inherit");
            }); //subquery for ShipDesc. Must append in order or title can end up on bottom due to response time

            shipId = $.get("/EveShipIDQuiz/GetShipId", { id: question })
            .done(function (shipid) {
                $("#shipimg").css("width", "256px");
                $("#shipimg").css("height", "256px");
                $("#shipimg").attr("src", "images/Renders/" + shipid + ".png");

                if (answer == correctanswer) {
                    HandleRightAnswer(shipid);
                }
                else {
                    HandleWrongAnswer(shipid, correctanswer);
                }

                var nbrAnswered = GetNbrAnswered();

                //----------------------------
                var mystring = TallyScore();
                //alert("mystring=" + mystring);
                //------------------------------

                if (nbrAnswered == 20) {
                    $("#completiondiv").text("Complete Quiz");
                }


            });  //subquery for shipID. use it both to set correct/incorrect status and to populate the image.


        });       //end correct answer query

        $("#completionstatus").text('nextquestion');
      

    }

    function GetNbrAnswered() {
        var score = $("#endValue").val();
        var scoreArray = score.split("|");
        nbrAnswered = (scoreArray.length - 1) / 2;
        return nbrAnswered;
    }

    function GetFinalScoreHTML() {

        var score = $("#endValue").val();
        var scoreArray = score.split("|");
        var shipIdArray = "";
        for (var j = 0; j < scoreArray.length; j++) {
        if(j%2 == 0)
        {
            shipIdArray = shipIdArray + scorearray[j] + ",";
        }
        }

           shipIdList = $.get("/EveShipIDQuiz/GetShipNames", { id: scoreArray })
            .done(function (shipIdList) {
            //add to list
            });
        
        html = "<tr><td>test1</td><td>test2</td></tr>";
        html = html + "</table>";
        return html;
    }

    function HandleRightAnswer(shipId) {
        score = $("#startValue").val();
        
        var newNbrCorrect = parseInt($("#nbrcorrect").text(), 10) + 1;
        $("#nbrcorrect").text(newNbrCorrect);
        $("#finalnbrcorrect").text(newNbrCorrect);

        $("#completiondiv").css("display", "inline-block");
        $("#completiondiv").css("background-color", "green");
        $("#shipdescription").css("background-color", "#002200");
        $("#endValue").val(score + shipId + "|1|");

    }

    function HandleWrongAnswer(shipId, rightAnswer) {
        score = $("#startValue").val();

        var newNbrIncorrect = parseInt($("#nbrincorrect").text(), 10) + 1;
        $("#nbrincorrect").text(newNbrIncorrect);
        $("#finalnbrincorrect").text(newNbrIncorrect);

        $("#completiondiv").css("display", "inline-block");
        $("#completiondiv").css("background-color", "red");
        $("#shipdescription").css("background-color", "#330000");

        var j = 0;
        $('input:radio').each(function () {
            j++;
            if ($(this).val() == rightAnswer) {
                $("#answer" + j).css("background-color", "green");
            }
        });
        $("#endValue").val(score + shipId + "|0|");
    }

    function CheckAnswer(i,bar) {
         if (($("#completionstatus").text() != "nextquestion")) {
            var elements = document.getElementsByName('typeOption');
            elements[i].checked = true;
            HandleAnswer();
        }
    }

    function TurnBlue(i) {
    if ($("#completionstatus").text() != "nextquestion") {
        $(i).css("background-color", "blue");
        $(i).css("color", "white");
        }
    }

    function TurnLightBlue(i) {
        if ($("#completionstatus").text() != "nextquestion") {
            $(i).css("background-color", "#3399FF");
            $(i).css("color", "black");
        }
    }

    function TallyScore()
    {
        var scoreString = $("#endValue").val();
        var bigArray = scoreString.split("|");
        var correctArray = [];
        var incorrectArray= [];

        for (var i = 0; i < bigArray.length; i++) {
            if (i % 2 == 0){
                correctArray.push(bigArray[i]);
            }
        }

        var returnedString = "";
        for (var j = 0; j < correctArray.length; j++) {
            returnedString += correctArray[j];
            returnedString += ";";
        }

        return returnedString;
    }


    // Determines if the passed element is overflowing its bounds,
    // either vertically or horizontally.
    // Will temporarily modify the "overflow" style to detect this
    // if necessary.
    //credit: Shog9 :: stackoverflow.com
    function checkOverflow(el) {
        var curOverflow = el.style.overflow;
        if (!curOverflow || curOverflow === "visible")
            el.style.overflow = "hidden";

        var isOverflowing = el.clientWidth < el.scrollWidth
      || el.clientHeight < el.scrollHeight;

        el.style.overflow = curOverflow;

        return isOverflowing;
    }


</script>

<a name="quizloc"></a>

<div id="quizpageheader" class="quizpageheader">
<div style="height:30%;padding:2px;display:table-cell;width:575px;">
<p id="score" class="headertext">
@if (@Model.score.Length == 0)
{
   <b>New Quiz</b>
}
else
{
        <b>Correct: <span id="nbrcorrect">@Model.getNbrCorrect()</span> | Incorrect: <span id="nbrincorrect">@Model.getNbrIncorrect()</span></b>
        <br />
        <a class="headeranchor" href="/EveShipIDQuiz?resetquiz=1">Start Over</a>
        
}
</p>    
</div>
<!--div id="advanced" style="display:none;">this is some stuff</div-->
<div style="text-align:right;display:table-cell;height:30%;padding:2px;width:575px;">

@using (Html.BeginForm("Index", "EveShipIDQuiz", FormMethod.Post, new { id = "nextQuestionForm", style = "visibility:visible;" }))
{
<!--form action="/EveShipIDQuiz" method="post" id="nextQuestionForm" style="visibility:hidden"-->
<input id="startValue" name="startValue" type="hidden" value="@Model.score"/>
<label>Include Capitals/Supers</label>
@Html.CheckBoxFor(model => model.quizDifficultyCaps)<br />
<label>Include Pirate/Rare</label>
@Html.CheckBoxFor(model => model.quizDifficultyPirateRare)
@Html.HiddenFor(model => model.endValue)
<input id="nextpagesubmit" type="submit" value="Next Page" hidden="hidden" />
}

<!--a onclick='$("#advanced").css("display","inline-block")' style="cursor:pointer;cursor:hand;"> Show Advanced Features</a-->
</div>
</div>

<div id="spacer" style="width:100%;height:1px;clear:both" >&nbsp;</div>

<div id="quizresults" class="quizresults">

  <h2>Final Score:</h2> <b>Correct: <span id="finalnbrcorrect">@Model.getNbrCorrect()</span> | Incorrect: <span id="finalnbrincorrect">@Model.getNbrIncorrect()</span></b>
   <br /><a style="vertical-align:top" href="/EveShipIDQuiz?resetquiz=1">Another Round?</a>
   <!--table id="resultstable"><tr><td style="width:250px">Correct Answers</td><td style="width:250px">Incorrect Answers</td></tr></table-->

</div>


<div id="innerquiz" class="innerquiz">

<div class="quizheader">@Model.ShipName</div>
<br />

<form id="quizform" style="display:none">
@foreach (var name in @Model.ShipTypeOptions)
{
    <input type="radio" name="typeOption" value="@name">@name <br/>
}
</input>

</form>

<div id="answer1" class="answerbar" onclick="CheckAnswer(0,this)" onmouseover="TurnBlue(this);" onmouseout="TurnLightBlue(this);" > @Model.ShipTypeOptions[0] </div>
<div id="answer2" class="answerbar" onclick="CheckAnswer(1,this)" onmouseover="TurnBlue(this);" onmouseout="TurnLightBlue(this);"> @Model.ShipTypeOptions[1] </div>
<div id="answer3" class="answerbar" onclick="CheckAnswer(2,this)" onmouseover="TurnBlue(this);" onmouseout="TurnLightBlue(this);"> @Model.ShipTypeOptions[2] </div>
<div id="answer4" class="answerbar" onclick="CheckAnswer(3,this)" onmouseover="TurnBlue(this);" onmouseout="TurnLightBlue(this);"> @Model.ShipTypeOptions[3] </div>

<br />


<div id="completiondiv" class="completion" onclick="NextQuestion();">Next Ship</div>


</div>

<div id="shipdescription" class="shipdescription">
<span id="correctshipname" style="font-size:large;font-weight:bold;" >&nbsp;</span>
<br />
<br />
<img id="shipimg" style="margin-left:175px;margin-right:auto;"/>
<br />
<span id="shipdescp" style="font-size:medium;text-align:left;">&nbsp;</span>
</div>

<div id="qmarkdiv" class="qmarkdiv">
<div id="qmarkspan" style="display:table-cell;margin-left:250px;vertical-align:middle;color:white;font-size:160px;text-align:center">?</div>
</div>

</div>


<label id="completionstatus" style="visibility:hidden">initial</label>


<div id="bottomspacer" style="width:90%;height:50px;clear:both;">&nbsp;</div>

<div id="footer" style="width:1150px;float:left;height:85px;border-style:solid;border-width:thin;overflow:hidden">
Website by fenjayminor (Twitter: <a href="http://twitter.com/fenjayminor" target="_blank">&#64;fenjayminor</a> / email fenjay at fenjaylabs). Feedback welcome!<br />
Assets/data ©CCP hf. All rights reserved. Used with permission.<br />
Background image by Smatilla: <a href="http://smattila.deviantart.com/" target="_blank">http://smattila.deviantart.com/</a> <a href="http://creativecommons.org/licenses/by-nc/3.0/" target="_blank">CC BY-NC 3.0</a> <br />
Special thanks to my alliance mates at <a href="http://aba-eve.com/index.php" target="_blank">A Band Apart</a> for early testing and feedback.<br />
<a href="/Roadmap">Quiz Development Roadmap</a><br /> 
</div>    
    