Eve-Ship-ID/Controllers/CorpSecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eve_api;
using Eve_Ship_ID.Models;

namespace Eve_Ship_ID.Controllers
{
    public class CorpSecurityController : Controller
    {
        //
        // GET: /CorpSecurity/

        public ActionResult Index()
        {       
            //get corp list
            return View();
        }

        public ActionResult RefreshCorporation(string id)
        {
            var data = new CorpSecurityModel();

              var idParsed = 0;

            //add bourbon and blasters for testing
              if (Int32.TryParse(id, out idParsed) && idParsed == 98340372) //or another valid value
              {
                  data.RefreshCorpRoster(idParsed);
              }

              return Redirect("../CorporationView/" + id);
            
        }

        public ActionResult CorporationView(string id) //(int CorpId)  //maybe change parameter to a or hidden param later
        {
            var data = new CorpSecurityModel();
            var idParsed = 0;

            if (Int32.TryParse(id,out idParsed) && idParsed == 98340372) //or another valid value
            {
                data.GetCorpInfo(idParsed);
                if (data.corpInfo.CorpName != string.Empty)
                {
                    data.ValidCorpId = true;
                    data.PopulateCorpRoster(idParsed);
                }
                else
                {
                    data.ValidCorpId = false;
                }

            }
            else
            {
                data.ValidCorpId = false;
            }

            return View(data);
        }

        public ActionResult EveCharacterEdit(string id)
        {
            var data = new EveCharacterModel();
            var idParsed = 0;

            if (Int32.TryParse(id, out idParsed)) //or another valid value
            data.RetrieveCharacter(idParsed);

            return View(data);
        }

        [HttpPost]
        public ActionResult EveCharacterEdit(EveCharacterModel updatedCharacter)
        {
            System.Diagnostics.Debug.Write(updatedCharacter.EveCharacter.comments);
            
            updatedCharacter.SaveCharacter();

            return new RedirectResult("../CorporationView/" + updatedCharacter.EveCharacter.corpID.ToString());
        }

        public string IsApiExpired(string id)
        {
            if (id == null) { return "REQUIRED: characterId,api,vCode"; }

            var pm = id.Split(new string[] { "," }, StringSplitOptions.None);

            if ((pm.Length == 3) && (pm[0] != string.Empty) && (pm[1] != string.Empty) && (pm[2] != string.Empty))
            {
                var characterid = pm[0];
                var api = pm[1];
                var vcode = pm[2];


                if (eve_api.eve_corp_security_api.IsCharacterAPIExpired(characterid, api, vcode))
                {
                    return "YES";
                }
                else
                {
                    return "NO";
                }
            }

            return "INVALID";
        }

    }
}

Eve-Ship-ID/Views/CorpSecurity/CorporationView.cshtml
@model Eve_Ship_ID.Models.CorpSecurityModel
@{
    ViewBag.Title = "CorporationView";
}
<link rel="stylesheet" type="text/css" href="Content/site.css"> 

<div class="siteheader">
<a href="http://www.fenjaylabs.com"><img src="images/fenjaylabs_logo.gif" /></a>
</div>


<div class="maincontent">
@if (Model.ValidCorpId)
{
    <div style="width:400px;float:left"><img src="@Model.CorpImgURL" /> <br />Editing Corporation:<p style="font-weight:bold"> @Model.corpInfo.CorpName</p></div> 
    if (Model.AllianceURL != string.Empty)
    {
    <div style="width:400px;float:right">
    <img src ="@Model.AllianceURL" /> <br /> Alliance: <p style="font-weight:bold">@Model.corpInfo.AllianceName </p>
    </div> 
     }   

    
<table class = "corplisting">
<tr><th>Name</th><th>Title(s)</th><th>Comments</th></tr>
@foreach (var evechar in Model.corpRoster.Values)
{
        <tr><td><a href="../EveCharacterEdit/@evechar.id"> @evechar.characterName </a></td><td>@evechar.rankTitles</td><td>@evechar.comments</td></tr>
}
</table>
}
else
{
<h3>Corp ID Not Valid</h3>
}
<br />
<br />
<a href="/BlackListMx">Blacklist Maintenance</a>
<br />
<br />
<a href="../RefreshCorporation/98340372">Refresh Corp Roster from API</a>
<div style="align:center;color:Red;">@Model.errorMessage</div>
</div>

<div class="contactfooter"> <!--style="border-top:20px;margin-left:65px;width:980px;background-color:#202020;"-->
<p style="color:White">Contact Me:<br />
Twitter:&nbsp;<a href="http://twitter.com/fenjayminor" target="_blank">Fenjayminor</a><br />
Email: fenjay at fenjaylabs<br />
</p>
</div>

Eve-Ship-ID/Views/CorpSecurity/EveCharacterEdit.cshtml
@model Eve_Ship_ID.Models.EveCharacterModel
@{
    ViewBag.Title = "EveCharacterEdit";
}
<script>
 function GetApiStatus() {

     characterId = $('#EveCharacter_characterEveID').val();
     api = $('#EveCharacter_characterApiID').val();
     vcode = $('#EveCharacter_characterApiVcode').val();

     /*alert(characterId);
     alert(api);
     alert(vcode);
     */

     query = characterId + ',' + api + ',' + vcode;
     //alert(query);
     
     $.get("../IsApiExpired/", { id: query })
        .done(function (isapiexpired) {
            if (isapiexpired == 'YES') {
                $("#ApiCheckResult").append("EXPIRED");
                $("#ApiCheckResult").css("visibility", "visible");
                $("#checkApi").css("visibility", "hidden");
            }
            else {
                $("#ApiCheckResult").append("VALID");
                $("#ApiCheckResult").css("visibility", "visible");
                $("#checkApi").css("visibility", "hidden");
            }
        }); 
            
}

</script>



<div class="siteheader">
<a href="http://www.fenjaylabs.com"><img src="../images/fenjaylabs_logo.gif" /></a>
</div>


<div class="maincontent">
<a href = "../CorporationView/@Model.EveCharacter.corpID">&lt;&lt; Back To Corporation View</a><br /><br />

<img src="@Model.ImgURL" />

@using (Html.BeginForm("EveCharacterEdit", "CorpSecurity", FormMethod.Post, new { id = "EveCharacterEditForm", style = "visibility:visible;" }))
{
<div class="div-table">
<div class="div-table-caption">Edit Character: @Model.EveCharacter.characterName</div>
<div class="div-table-row">
<div class="div-table-col">Title(s)</div>
<div class="div-table-col">
    @Html.TextBoxFor(model => model.EveCharacter.rankTitles, new {@readonly = "readonly", style = "background-color:gray"})
    </div>
</div>
<div class="div-table-row">
<div class="div-table-col">API ID <br /> ApiVCode</div>
<div class="div-table-col">@Html.TextBoxFor(model => model.EveCharacter.characterApiID) <br /> @Html.TextBoxFor(model => model.EveCharacter.characterApiVcode)
<br /> <div id="checkApi"><a onclick="GetApiStatus()" style="cursor:pointer">Check API for Validity</a></div><div id="ApiCheckResult" style="visibility:hidden;color:Red;"></div>
</div>
</div>
<div class="div-table-row">
<div class="div-table-col">Is a current member</div>
<div class="div-table-col">@Html.CheckBoxFor(model => model.EveCharacter.currentMember, new { @readonly = "readonly", style = "background-color:gray" })</div>
</div>
<div class="div-table-row">
<div class="div-table-col">Is a prospect</div>
<div class="div-table-col">@{object prospectprops = (Model.EveCharacter.currentMember) ? new {@readonly = "readonly", style = "background-color:gray"}  : null;
    @Html.CheckBoxFor(model => model.EveCharacter.prospect, prospectprops)
}</div>
</div>
<div class="div-table-row">
<div class="div-table-col">Blacklisted</div>
<div class="div-table-col">@{object blprops = (Model.EveCharacter.currentMember) ? new { @readonly = "readonly", style = "background-color:gray" } : null;
    @Html.CheckBoxFor(model => model.EveCharacter.blacklist, blprops)
}</div>
</div>
<div class="div-table-row">
<div class="div-table-col">Main's name (if applicable)</div>
<div class="div-table-col">@Html.TextBoxFor(model => model.MainCharacterName)
</div>
</div>
<div class="div-table-row">
<div class="div-table-col">Comments</div>
<div class="div-table-col">@Html.TextAreaFor(model => model.EveCharacter.comments)</div>
</div>
</div>
    @Html.HiddenFor(model => model.EveCharacter.altMainCharacterId)
    @Html.HiddenFor(model => model.EveCharacter.corpID)
    @Html.HiddenFor(model => model.EveCharacter.characterEveID)
    @Html.HiddenFor(model => model.EveCharacter.id)
    <input id="submitchar" type="submit" value="Update Character" />
}

</div>

Eve-Ship-ID/Views/CorpSecurity/Index.cshtml
@model Eve_Ship_ID.Models.CorpSecurityModel
@{
    ViewBag.Title = "Eve Online Corp Security";
}


<link rel="stylesheet" type="text/css" href="Content/site.css"> 

<div class="siteheader">
<a href="http://www.fenjaylabs.com"><img src="images/fenjaylabs_logo.gif" /></a>
</div>


<div class="maincontent">
<table class = "corplisting">
<tr><th>Name</th></tr>
<tr><td><a href="CorpSecurity/CorporationView/98340372">SUPREME MATHEMATICS</a></td></tr>
</table>
</div>

<div class="contactfooter"> 
<p style="color:White">Contact Me:<br />
Twitter:&nbsp;<a href="http://twitter.com/fenjayminor" target="_blank">Fenjayminor</a><br />
Email: fenjay at fenjaylabs<br />
</p>
</div>